# docker-compose.yml
# This file is used to define and run multi-container Docker applications.
# It sets up a Spring Boot application with a MySQL database.
services:
  app:
    image: thanhhoan99/javatest-movie:latest
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/movies?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 0908
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 0908
      MYSQL_DATABASE: movies
      # MYSQL_USER: root
      # MYSQL_PASSWORD: 0908
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql
    healthcheck:
      # This healthcheck ensures that the MySQL service is ready before the app starts.
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p0908']
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s
volumes:
  db_data: